image_width: 1440
image_height: 1080
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [1747.88128,    0.     ,  733.59973,
            0.     , 1753.29899,  563.44331,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.101372, 0.127723, 0.000117, -0.000738, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [1722.59399,    0.     ,  732.68001,    0.     ,
            0.     , 1736.55664,  563.33614,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]