name: rm_vision CI

on:
  push:
    branches:
      - main  # 或你用于部署的分支名


jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        docker build -t your-image-name:latest .

    - name: Save Docker image
      run: |
        mkdir -p docker # 创建目录，如果已存在则不会有影响
        docker save your-image-name:latest > docker/your-image-name.tar

